spring:
  application:
    name: demo
  datasource:
    url: jdbc:informix-sqli://<DB_HOST_IP>:<DB_PORT>/<DB_NAME>
    ##e.g jdbc:informix-sqli://127.0.0.1:9214/test_db
    username: <DB_USERNAME>
    password: <DB_PASSWORD>
    driver-class-name: com.informix.jdbc.IfxDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.InformixDialect

server:
  port: 8085